paths:
  data_path:   "data/final_data.xlsx"
  scaling_path: "data/scaling_df.xlsx"
  model_dir:   "out/models"
  model_path:  "out/models/best_model.pkl"
  output_path: "out/predictions.parquet"
  logging_path: "logs/run.log"

data:
  countries: ["AUS","CAN","GER","FRA","IND","JAP","USA","UK"]
  lower_quantile: 0.05
  upper_quantile: 0.95

model:
  mlflow:
    enable: true
    experiment_name: "Docstar Sales Forecasting"
  estimator: "XGBoost"
  test_size: 0.2
  params:
    XGBoost:
      estimator__n_estimators: [150, 300, 450]
      estimator__max_depth: [3, 5, 10]
      estimator__learning_rate: [0.01, 0.1, 0.2]
      estimator__subsample: [0.75, 0.9, 1]
    RandomForest:
      estimator__n_estimators: [100, 200, 300]
      estimator__max_depth: [3, 5, 10]
    LightGBM:
      estimator__n_estimators: [100, 200]
      estimator__learning_rate: [0.05, 0.1]
  n_iter: 4
  cv_folds: 5
  target_col: "Sales"
  random_state: 42
  scoring: "neg_root_mean_squared_error"
