paths:
  data_path:   "../data/final_data.xlsx"
  scaling_path: "../data/scaling_df.csv"
  model_dir:   "../out/models"
  model_path:  "../out/models/best_model.pkl"
  output_path: "../out/predictions.parquet"

model:
  estimator: "XGBoost"
  random_forest:
    n_estimators: 100
    max_depth: null
    random_state: 42
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    objective: "reg:squarederror"
    random_state: 42

training:
  test_size: 0.2
  random_state: 42

inference:
  batch_size: 32

evaluation:
  metrics:
    - rmse
    - r2
    - mae
